### ISSUE TITLE
Sub menu items with the same name are not unique

### ISSUE THREAD

**Issue by LarsDenBakker** [daKmoR/rocket#21]
I have two sub menu items with the same name. Select one makes both highlighted.

![image](https://user-images.githubusercontent.com/11994993/89717423-df309600-d9b6-11ea-852f-5c22ecf6df74.png)

**Comment by LarsDenBakker** [comment]
Sub menu items get duplicated as well, maybe they share the same key:

![image](https://user-images.githubusercontent.com/11994993/89717538-d42a3580-d9b7-11ea-9f45-9a10f584dfae.png)

**Comment by daKmoR** [comment]
Indeed keys need to be unique... as they are used throughout the code to create the "tree"

you can, however, use a best practice to have "unique keys" by doing `Parent > Child`.
If you do so you probably want to separately provide a `title` which will be displayed in the menu instead of the key.

```
test-runner/index.md
---
title: Test Runner
eleventyNavigation:
  key: Test Runner
---

test-runner/overview.md
---
title: Web Test Runner Overview
eleventyNavigation:
  key: Test Runner > Overview
  title: Overview
  parent: Test Runner
---
```

I will leave this open as we should definitely document this 👍

**Comment by daKmoR** [comment]
closed by https://github.com/daKmoR/rocket/pull/51
